#!/bin/bash

# -----------------------------------------------------------------
#
# Describe script purpose here.
#
# -----------------------------------------------------------------
#
# Push assets to a remote host. Be VERY CAREFULL with the --delete
# option!!! Terrible data loss has happen in the past.
#  
# -----------------------------------------------------------------

# Check mlkcontext to check. If void, no check will be performed
MATCH_MLKCONTEXT=XXX
# Source folder, can be the folder itself.
SOURCE_FOLDER=.
# Remote folder, this folder will be created at the remote if possible
# Use absolute paths exclusively.
REMOTE_FOLDER=XXX
# Remote SSH username
USER_NAME=XXX
# Host
HOST=XXX
# Excludes, for example ("a*" "e*" "r*") 
EXCLUDES=(
  ".DS_Store" "rsync*" ".gitignore" ".git"
)
# SSH port
SSH_PORT=22
# Amazon AWS PEM key (it´s a path to a file, or blank if none)
AWS_PEM=
# Dry run
DRY_RUN=true
# Delete. BEWARE!!!
DELETE=true





# ---

# Check mlkcontext

if [ ! -z "${MATCH_MLKCONTEXT}" ] ; then

  if [ ! "$(mlkcontext)" = "$MATCH_MLKCONTEXT" ] ; then

    echo Please initialise context $MATCH_MLKCONTEXT

    exit 1

  fi

fi


# Initial options for SSH and RSYNC

SSH_OPTIONS="-p ${SSH_PORT}"


# Amazon PEM

if [ ! -z $AWS_PEM ] ; then

  SSH_OPTIONS="${SSH_OPTIONS} -i ${AWS_PEM}"

fi


# If


# BEWARE THE DELETE!!!

if [ "$DELETE" = true ] ; then 

  DELETE="--delete"
  
else 

  DELETE=""
  
fi


# Dry run

if [ "$DRY_RUN" = true ] ; then 

  DRY_RUN_F="--dry-run"
  
else 

  DRY_RUN_F=""
  
fi


# The command

RSYNC="rsync -avzhr --progress ${DELETE} ${DRY_RUN_F} --rsh=\"ssh ${SSH_OPTIONS}\" "


# Process of excludes

for EXCLUDE in "${EXCLUDES[@]}" ; do

  RSYNC="${RSYNC} --exclude \"${EXCLUDE}\""

done


# Command

RSYNC="${RSYNC} ${SOURCE_FOLDER} ${USER_NAME}@${HOST}:${REMOTE_FOLDER}"

eval $RSYNC


# Make all .sh executable

if [ "$DRY_RUN" = false ] ; then

  ssh $SSH_OPTIONS $USER_NAME@$HOST "chmod -R 755 ${REMOTE_FOLDER}/*.sh"

fi
